name: Feature request
description: Suggest an improvement
title: "[Feature] "
labels: ["enhancement"]
body:
  - type: textarea
    id: idea
    attributes:
      label: What would you like?
      description: Describe the feature
    validations:
      required: true

  - type: textarea
    id: why
    attributes:
      label: Why is this useful?
